### PR TITLE
feat: limit maximum reactions per user per post

### PR DESCRIPTION
**Pull request by ShlomoCode**
Added a setting to limit the amount of new comments per user per post, similar to the limit of votes in nodebb.

CleanShot 2023-05-11 at 04 09 11@2x

### CODE REVIEW

**Comment by ShlomoCode** [comment]
I think it might be worth unhiding the add comment button in case the comment limit for the post has been reached, but when you try to click, an error will appear.
This is a more predictable and structured behavior, because it is like the built-in like buttons.

**Comment by barisusakli** [comment]
thanks, published 2.0.1

**Comment by ShlomoCode** [comment]
@barisusakli it doesn't matter much, but doesn't adding a feature mean a minor version - 2.1?

**Comment by barisusakli** [comment]
Plugins don't really follow semver strictly like core nodebb. this isn't a breaking change so 2.0.1 is fine.

**Pull request merged**
