### PR TITLE
Feat: Refactor

### PR DESCRIPTION
**Pull request by Antosik**
**Done**:
- **Breaking Change**
  - use `<!-- IMPORT ... -->` to render the reactions panel 
- Backend part 
  -  was rewritten from callbacks via `async` dependency to native async/await (7645fb6)
  -  count of calls to the database was optimized (7645fb6)
- Frontend part
  - use new `hooks` module (0ff4613)
  - deprecated `Benchpress.parse` was replaced with `app.parseAndTranslate` (0ff4613)
  - tooltips now displayed when new reaction was added (99b45c5)
- Misc
  - updated `peerDependency` for `nodebb-plugin-emoji` (543de16)
  - updated nodeBB compatibility (543de16)

### CODE REVIEW

**Comment by barisusakli** [comment]
@pichalite can you merge this or transfer this repo to nodebb-community?

**Comment by pichalite** [comment]
@barisusakli looks like a fork of this plugin already exists in nodebb-community. If you remove that, I can transfer this repo there.

**Comment by barisusakli** [comment]
OK, deleted the fork in nodebb-community

**Comment by pichalite** [comment]
@barisusakli transfer complete

**Comment by barisusakli** [comment]
Thank you! 👍🏼

**Pull request merged**
